language: node_js
sudo: false
node_js:
  - "0.12"
# Send coverage data to Coveralls
# xxafter_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
# Send coverage data to codeclimate
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info