language: node_js
sudo: false
node_js:
  - "0.12"
  - "4.4"
  - "5.1"

# Send coverage data to Coveralls and codeclimate
after_script:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - cat ./coverage/*/lcov.info | ./node_modules/codeclimate-test-reporter/bin/codeclimate.js